# Generated by Django 5.0.1 on 2024-03-04 17:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_task_datecompleted_alter_task_field'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion', models.DecimalField(decimal_places=2, max_digits=5)),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.task')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark1', models.PositiveIntegerField(blank=True, null=True, verbose_name='nota1')),
                ('mark2', models.PositiveIntegerField(blank=True, null=True, verbose_name='nota2')),
                ('mark3', models.PositiveIntegerField(blank=True, null=True, verbose_name='nota3')),
                ('average', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='promedio')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'nota',
                'verbose_name_plural': 'notas',
            },
        ),
    ]
