# Generated by Django 5.0.1 on 2024-03-06 05:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_calificacion_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calificacion',
            name='tareas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.task'),
        ),
    ]
